module MRBGemify
  REQUIRED_FILES = ["./mrblib/mspec/**/*.rb", './mrblib/mspec.rb']

  MRBGEM_TEMPLATE = <<-END_OF_MRBGEM_TEMPLATE.strip
# This file was generated by the mrbgemify rake task
# You may provide additional configuration in an mrbgem.ext.rake file.
# Alternatively, you can edit the template for this file in mrbgemify.conf.rb

MRuby::Gem::Specification.new('mruby-mspec') do |spec|
  spec.author = 'Jared Breeden'
  spec.summary = 'MSpec as an mrbgem'
  spec.license = 'MIT'

  spec.add_dependency 'mruby-apr'

  spec.rbfiles = [
    File.absolute_path("../mrblib/require_patch.rb", __FILE__),
<% required_files.each do |file| -%>
    File.absolute_path(<%= JSON.dump(file).sub(File.absolute_path('.'), '..') %>, __FILE__),
<% end -%>
    File.absolute_path("../mrblib/require_restore.rb", __FILE__),
    File.absolute_path("../mrblib/builtin_features.rb", __FILE__)
  ]

  mrbgem_ext_rake = File.absolute_path('../mrbgem.ext.rake', __FILE__)
  if File.exists?(mrbgem_ext_rake)
    require 'stringio'
    io = StringIO.new
    io.print "proc { |spec|; "
    io.puts File.read(mrbgem_ext_rake)
    io.puts "}"
    p = eval(io.string)
    p[spec]
  end
end
  END_OF_MRBGEM_TEMPLATE
end
